# Generated by Django 4.0 on 2021-12-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_view', '0003_rename_prix_ht_data_view_prix_ht_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_view',
            name='index',
            field=models.IntegerField(null=True),
        ),
    ]
